[2024-01-25T21:16:50.579+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cvd_automation_pipeline.run_nuclei_scan_task manual__2024-01-25T21:16:48.594003+00:00 [queued]>
[2024-01-25T21:16:50.586+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cvd_automation_pipeline.run_nuclei_scan_task manual__2024-01-25T21:16:48.594003+00:00 [queued]>
[2024-01-25T21:16:50.586+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-01-25T21:16:50.598+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_nuclei_scan_task> on 2024-01-25 21:16:48.594003+00:00
[2024-01-25T21:16:50.602+0000] {standard_task_runner.py:60} INFO - Started process 3094 to run task
[2024-01-25T21:16:50.603+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cvd_automation_pipeline', 'run_nuclei_scan_task', 'manual__2024-01-25T21:16:48.594003+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/test_pipeline_dag.py', '--cfg-path', '/tmp/tmp7cfzo5nd']
[2024-01-25T21:16:50.605+0000] {standard_task_runner.py:88} INFO - Job 26: Subtask run_nuclei_scan_task
[2024-01-25T21:16:50.638+0000] {task_command.py:423} INFO - Running <TaskInstance: cvd_automation_pipeline.run_nuclei_scan_task manual__2024-01-25T21:16:48.594003+00:00 [running]> on host d1dec68e083c
[2024-01-25T21:16:50.693+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cvd_automation_pipeline' AIRFLOW_CTX_TASK_ID='run_nuclei_scan_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-25T21:16:48.594003+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-25T21:16:48.594003+00:00'
[2024-01-25T21:16:50.757+0000] {logging_mixin.py:188} INFO - An error occurred while running Nuclei command: Command 'nuclei -H 'User-Agent: DIVD-2023-00020' -t /opt/***/data/fingerprint_gamingteam.yaml -l data/2024-01-25-shodan-results.csv -retries 2 -timeout 6 -output data/2024-01-25-nuclei-results.json -json' returned non-zero exit status 2.
[2024-01-25T21:16:50.758+0000] {logging_mixin.py:188} INFO - Nuclei scan completed.
[2024-01-25T21:16:50.758+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-01-25T21:16:50.767+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=cvd_automation_pipeline, task_id=run_nuclei_scan_task, execution_date=20240125T211648, start_date=20240125T211650, end_date=20240125T211650
[2024-01-25T21:16:50.817+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-25T21:16:50.836+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
