[2024-01-25T20:44:14.776+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cvd_automation_pipeline.run_nuclei_scan_task manual__2024-01-25T20:44:12.861800+00:00 [queued]>
[2024-01-25T20:44:14.785+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cvd_automation_pipeline.run_nuclei_scan_task manual__2024-01-25T20:44:12.861800+00:00 [queued]>
[2024-01-25T20:44:14.786+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-01-25T20:44:14.799+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_nuclei_scan_task> on 2024-01-25 20:44:12.861800+00:00
[2024-01-25T20:44:14.803+0000] {standard_task_runner.py:60} INFO - Started process 1932 to run task
[2024-01-25T20:44:14.805+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cvd_automation_pipeline', 'run_nuclei_scan_task', 'manual__2024-01-25T20:44:12.861800+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/test_pipeline_dag.py', '--cfg-path', '/tmp/tmpmbcc3zdh']
[2024-01-25T20:44:14.807+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask run_nuclei_scan_task
[2024-01-25T20:44:14.843+0000] {task_command.py:423} INFO - Running <TaskInstance: cvd_automation_pipeline.run_nuclei_scan_task manual__2024-01-25T20:44:12.861800+00:00 [running]> on host d1dec68e083c
[2024-01-25T20:44:14.901+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cvd_automation_pipeline' AIRFLOW_CTX_TASK_ID='run_nuclei_scan_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-25T20:44:12.861800+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-25T20:44:12.861800+00:00'
[2024-01-25T20:44:14.968+0000] {logging_mixin.py:188} INFO - An error occurred while running Nuclei command: Command 'nuclei -H 'User-Agent: DIVD-2023-00020' -t /opt/***/data/fingerprint_data.yaml -l data/2024-01-25-shodan-results.csv -retries 2 -timeout 6 -output data/2024-01-25-nuclei-results.json -json' returned non-zero exit status 2.
[2024-01-25T20:44:14.969+0000] {logging_mixin.py:188} INFO - Nuclei scan completed.
[2024-01-25T20:44:14.970+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-01-25T20:44:14.978+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=cvd_automation_pipeline, task_id=run_nuclei_scan_task, execution_date=20240125T204412, start_date=20240125T204414, end_date=20240125T204414
[2024-01-25T20:44:15.018+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-25T20:44:15.036+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
