[2024-01-25T23:40:48.474+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cvd_automation_pipeline.run_nuclei_scan_task manual__2024-01-25T23:40:39.438862+00:00 [queued]>
[2024-01-25T23:40:48.484+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cvd_automation_pipeline.run_nuclei_scan_task manual__2024-01-25T23:40:39.438862+00:00 [queued]>
[2024-01-25T23:40:48.484+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-01-25T23:40:48.497+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_nuclei_scan_task> on 2024-01-25 23:40:39.438862+00:00
[2024-01-25T23:40:48.502+0000] {standard_task_runner.py:60} INFO - Started process 342 to run task
[2024-01-25T23:40:48.504+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cvd_automation_pipeline', 'run_nuclei_scan_task', 'manual__2024-01-25T23:40:39.438862+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/cvd_pipeline_1.py', '--cfg-path', '/tmp/tmpfum5bxh9']
[2024-01-25T23:40:48.506+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask run_nuclei_scan_task
[2024-01-25T23:40:48.541+0000] {task_command.py:423} INFO - Running <TaskInstance: cvd_automation_pipeline.run_nuclei_scan_task manual__2024-01-25T23:40:39.438862+00:00 [running]> on host 6cac4319e35a
[2024-01-25T23:40:48.596+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cvd_automation_pipeline' AIRFLOW_CTX_TASK_ID='run_nuclei_scan_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-25T23:40:39.438862+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-25T23:40:39.438862+00:00'
[2024-01-25T23:41:00.930+0000] {logging_mixin.py:188} INFO - An error occurred while running Nuclei command: Command 'nuclei -H 'User-Agent: DIVD-2023-00020' -t /opt/***/fingerprint_gamingteam.yaml -l data/2024-01-25-shodan-results.csv -retries 2 -timeout 6 -output data/2024-01-25-nuclei-results.json -j' returned non-zero exit status 1.
[2024-01-25T23:41:00.931+0000] {logging_mixin.py:188} INFO - None
[2024-01-25T23:41:00.932+0000] {logging_mixin.py:188} INFO - Nuclei scan completed.
[2024-01-25T23:41:00.933+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-01-25T23:41:00.942+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=cvd_automation_pipeline, task_id=run_nuclei_scan_task, execution_date=20240125T234039, start_date=20240125T234048, end_date=20240125T234100
[2024-01-25T23:41:00.981+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-25T23:41:01.000+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
